"""Repository ports — async persistence boundaries for aggregate roots."""

from __future__ import annotations

from typing import Protocol

from domain.entities.custom_object import CustomObject
from domain.entities.programme import Programme
from domain.entities.remediation import RemediationSuggestion
from domain.entities.sap_landscape import SAPLandscape
from domain.value_objects.object_type import CompatibilityStatus


class ProgrammeRepositoryPort(Protocol):
    async def save(self, programme: Programme) -> None: ...
    async def get_by_id(self, id: str) -> Programme | None: ...
    async def list_by_customer(self, customer_id: str) -> list[Programme]: ...
    async def list_all(self) -> list[Programme]: ...


class LandscapeRepositoryPort(Protocol):
    async def save(self, landscape: SAPLandscape) -> None: ...
    async def get_by_id(self, id: str) -> SAPLandscape | None: ...
    async def list_by_programme(self, programme_id: str) -> list[SAPLandscape]: ...


class CustomObjectRepositoryPort(Protocol):
    async def save(self, obj: CustomObject) -> None: ...
    async def save_batch(self, objs: list[CustomObject]) -> None: ...
    async def get_by_id(self, id: str) -> CustomObject | None: ...
    async def get_by_landscape(self, landscape_id: str) -> list[CustomObject]: ...
    async def list_by_landscape(self, landscape_id: str) -> list[CustomObject]: ...
    async def count_by_status(self, landscape_id: str, status: CompatibilityStatus) -> int: ...


class RemediationRepositoryPort(Protocol):
    async def save(self, suggestion: RemediationSuggestion) -> None: ...
    async def save_batch(self, suggestions: list[RemediationSuggestion]) -> None: ...
    async def get_by_object(self, object_id: str) -> list[RemediationSuggestion]: ...
    async def get_by_object_ids(self, object_ids: list[str]) -> list[RemediationSuggestion]: ...
    async def list_by_programme(self, programme_id: str) -> list[RemediationSuggestion]: ...
