"""File storage port — boundary for blob/object storage infrastructure."""

from __future__ import annotations

from typing import Protocol


class FileStoragePort(Protocol):
    async def upload(self, path: str, file_bytes: bytes) -> str: ...
    async def download(self, path: str) -> bytes: ...
    async def delete(self, path: str) -> bool: ...
    async def list_files(self, prefix: str) -> list[str]: ...
